const WHATSAPP_NUMBER = '355692100222';
const currency = new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const products = [
 {id:'iphone-16-pro-max',cat:'iPhone',name:'iPhone 16 Pro Max',price:1199,storage:'256GB',color:'Desert Titanium',img:'/assets/products/iphone-16-pro-max.svg',desc:'Flagship iPhone experience with titanium design, ProMotion display and pro camera system for premium users.',features:['6.9” Super Retina XDR','A18 Pro chip','Pro camera system','USB‑C / MagSafe'],badges:['Europe CE','Warranty','Top Seller']},
 {id:'iphone-16-pro',cat:'iPhone',name:'iPhone 16 Pro',price:1050,storage:'128GB',color:'Natural Titanium',img:'/assets/products/iphone-16-pro.svg',desc:'Compact Pro power with premium titanium finish, smooth 120Hz display and advanced camera controls.',features:['6.3” OLED display','A18 Pro','120Hz ProMotion','Titanium finish'],badges:['Pro','CE','Available']},
 {id:'iphone-16',cat:'iPhone',name:'iPhone 16',price:829,storage:'128GB',color:'Ultramarine',img:'/assets/products/iphone-16.svg',desc:'Modern iPhone with Dynamic Island, bright OLED screen and fast everyday performance.',features:['6.1” OLED','Dynamic Island','A18 chip','48MP main camera'],badges:['New','CE','Best Value']},
 {id:'iphone-15-pro-max',cat:'iPhone',name:'iPhone 15 Pro Max',price:899,storage:'256GB',color:'Black Titanium',img:'/assets/products/iphone-15-pro-max.svg',desc:'Premium previous-generation Pro Max with titanium body and excellent battery life.',features:['Titanium design','USB‑C','Pro cameras','Large display'],badges:['Premium Deal','Warranty']},
 {id:'airpods-pro-2',cat:'Audio',name:'AirPods Pro 2',price:249,storage:'USB‑C',color:'White',img:'/assets/products/airpods-pro-2.svg',desc:'Premium in-ear audio with Active Noise Cancellation, Adaptive Audio and MagSafe charging case.',features:['ANC','Adaptive Audio','Spatial Audio','MagSafe Case'],badges:['Original','Audio']},
 {id:'airpods-max',cat:'Audio',name:'AirPods Max',price:549,storage:'USB‑C',color:'Silver',img:'/assets/products/airpods-max.svg',desc:'Over-ear premium listening experience with cinematic sound and iconic Apple design.',features:['Hi‑Fi sound','ANC','Spatial Audio','Aluminium design'],badges:['Luxury Audio']},
 {id:'watch-ultra-2',cat:'Watch',name:'Apple Watch Ultra 2',price:799,storage:'GPS + Cellular',color:'Black Titanium',img:'/assets/products/watch-ultra-2.svg',desc:'The rugged premium Apple Watch with titanium case, bright display and advanced sport features.',features:['49mm titanium','Always‑On display','100m water resistant','Dual-frequency GPS'],badges:['Ultra','Titanium']},
 {id:'macbook-air-m3',cat:'Mac',name:'MacBook Air M3',price:1099,storage:'256GB SSD',color:'Midnight',img:'/assets/products/macbook-air-m3.svg',desc:'Thin, silent and powerful MacBook for study, business and premium daily work.',features:['13.6” Liquid Retina','Apple M3','16GB available','All‑day battery'],badges:['Mac','Student Choice']},
 {id:'macbook-pro-m4',cat:'Mac',name:'MacBook Pro M4',price:1699,storage:'512GB SSD',color:'Space Black',img:'/assets/products/macbook-pro-m4.svg',desc:'Professional MacBook for creators, business users and maximum performance workflows.',features:['M4 chip','Liquid Retina XDR','Pro performance','Space Black'],badges:['Pro Work']},
 {id:'accessories',cat:'Accessories',name:'Premium Accessories',price:39,storage:'MagSafe',color:'Mixed',img:'/assets/products/accessories.svg',desc:'Cases, MagSafe chargers, cables and premium accessories selected for Apple users.',features:['MagSafe ready','Cases','Cables','Chargers'],badges:['Add‑ons']}
];
let activeFilter='all', searchTerm='', cart=[];
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function wa(text){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`}
function renderProducts(){
 const grid=qs('#productGrid');
 let list=products.filter(p=>(activeFilter==='all'||p.cat===activeFilter) && (p.name+p.desc+p.cat+p.color+p.storage).toLowerCase().includes(searchTerm));
 const sort=qs('#sort').value; if(sort==='priceAsc') list.sort((a,b)=>a.price-b.price); if(sort==='priceDesc') list.sort((a,b)=>b.price-a.price);
 grid.innerHTML=list.map(p=>`<article class="product-card reveal in"><div class="product-media"><img src="${p.img}" alt="${p.name}" loading="lazy"></div><div class="product-body"><div class="badges">${p.badges.map(b=>`<span class="badge">${b}</span>`).join('')}</div><h3>${p.name}</h3><p class="desc">${p.desc}</p><div class="features">${p.features.map(f=>`<span>${f}</span>`).join('')}</div><div class="price-row"><div><div class="price">${currency.format(p.price)}</div><small>${p.storage} · ${p.color}</small></div><button class="add" data-id="${p.id}">Add</button></div></div></article>`).join('') || '<p>No products found.</p>';
 qsa('.add').forEach(b=>b.onclick=()=>addToCart(b.dataset.id));
}
function addToCart(id){const p=products.find(x=>x.id===id); const existing=cart.find(x=>x.id===id); if(existing) existing.qty++; else cart.push({...p,qty:1}); renderCart(); qs('#cart').classList.add('open');}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id); renderCart();}
function renderCart(){qs('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0); qs('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><img src="${i.img}" alt="${i.name}"><div><b>${i.name}</b><small>${i.qty} × ${currency.format(i.price)} · ${i.storage}</small></div><button data-rm="${i.id}">×</button></div>`).join(''):'<p style="color:#a6a8b3">Your request is empty. Add products to generate a WhatsApp order.</p>'; qsa('[data-rm]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.rm)); const total=cart.reduce((s,i)=>s+i.price*i.qty,0); qs('#cartTotal').textContent=currency.format(total); const lines=cart.map(i=>`• ${i.qty}x ${i.name} — ${i.storage} / ${i.color} — ${currency.format(i.price)}`).join('\n'); qs('#checkout').href=wa(`Pershendetje Molla Shop, dua te porosis / kontrolloj disponueshmerine:\n\n${lines}\n\nTotali indikativ: ${currency.format(total)}\n\nJu lutem me dergoni konfirmim, gjendje dhe garanci.`)}
qsa('.collection-card').forEach(btn=>btn.onclick=()=>{qsa('.collection-card').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;renderProducts();location.hash='products'});
qs('#search').oninput=e=>{searchTerm=e.target.value.toLowerCase();renderProducts()}; qs('#sort').onchange=renderProducts;
qs('#cartFab').onclick=()=>qs('#cart').classList.add('open'); qs('#closeCart').onclick=()=>qs('#cart').classList.remove('open');
['#navWhatsApp','#videoWhatsApp','#storeWhatsApp'].forEach(sel=>{const el=qs(sel); if(el) el.href=wa('Pershendetje Molla Shop, dua informacion per produktet Apple dhe disponueshmerine aktuale.')});
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12}); qsa('.reveal').forEach(el=>io.observe(el));
window.addEventListener('load',()=>setTimeout(()=>qs('#loader').classList.add('hide'),450));
renderProducts(); renderCart();
